# Generated by Django 4.2.11 on 2024-04-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='YourSiteName', max_length=50)),
                ('phone', models.CharField(default='YourPhoneNumber', max_length=20)),
                ('email', models.EmailField(default='YourEmailName', max_length=50)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
